//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProveedorTuTienditaPS4.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class tutienditaps4_Entities : DbContext
    {
        public tutienditaps4_Entities()
            : base("name=tutienditaps4_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnunciarPago> AnunciarPago { get; set; }
        public virtual DbSet<Pack> Pack { get; set; }
        public virtual DbSet<PackJuego> PackJuego { get; set; }
        public virtual DbSet<PackOferta> PackOferta { get; set; }
        public virtual DbSet<ProveedorVenta> ProveedorVenta { get; set; }
        public virtual DbSet<ProveedorVentaEstado> ProveedorVentaEstado { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioPerfil> UsuarioPerfil { get; set; }
        public virtual DbSet<UsuarioPermisoSitio> UsuarioPermisoSitio { get; set; }
        public virtual DbSet<Venta> Venta { get; set; }
        public virtual DbSet<VentaEstado> VentaEstado { get; set; }
    
        public virtual ObjectResult<sp_ListarPackProveedor_Result> sp_ListarPackProveedor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListarPackProveedor_Result>("sp_ListarPackProveedor");
        }
    }
}
