//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProveedorTuTienditaPS4.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int idVenta { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> idPack { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idVentaEstado { get; set; }
    
        public virtual Pack Pack { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual VentaEstado VentaEstado { get; set; }
    }
}
